title: blog
description: developer notes
email: efrolov.app@gmail.com

baseurl: ""
url: "http://freekode.org"

disqus: freekode
google_analytics: UA-58135206-1
github_username:  freekode

markdown: kramdown
theme: minima
permalink: /:title/
